#!/bin/sh

DATE=$(date +"%Y-%m-%d %H:%M")
TEMP=$(sensors | grep "Core 0" | cut -d'(' -f1 | cut -d'+' -f2)

sed -i "1i$DATE    $TEMP" /home/httpd/html/dav/temp.txt
#sed -i "1i$DATE" /home/httpd/html/dav/notepad
ssh root@192.168.0.254 "cat /proc/net/arp|grep x2" > /home/httpd/html/dav/arp
